testes:
	iverilog Alu.v Comparator.v Control.v Decode.v Execute.v Fetch.v MemController.v Memory.v Mips.v Ram.v Registers.v Shifter.v Writeback.v tb0.v -o tb0
	iverilog Alu.v Comparator.v Control.v Decode.v Execute.v Fetch.v MemController.v Memory.v Mips.v Ram.v Registers.v Shifter.v Writeback.v tb1.v -o tb1
	iverilog Alu.v Comparator.v Control.v Decode.v Execute.v Fetch.v MemController.v Memory.v Mips.v Ram.v Registers.v Shifter.v Writeback.v tb2.v -o tb2